### ISSUE TITLE
Replace getProjectKey() with getScriptId() in 2-step flow.

### ISSUE THREAD

**Issue by airhadoken** [airhadoken/twitter-lib#15]
Google has deprecated the `ScriptApp.getProjectKey()` function but says that `getScriptId()` will work in all cases where `getProjectKey()` was needed.

https://developers.google.com/apps-script/reference/script/script-app#getScriptId()

**Comment by airhadoken** [comment]
For, reference, the Script ID for Twitter lib is `11dB74uW9VLpgvy1Ax3eBZ8J7as0ZrGtx4BPw7RKK-JQXyAJHBx98pY-7`

**Comment by airhadoken** [comment]
Closed via #18

**Comment by rahulserver** [comment]
@airhadoken 
I added script ID via the Resources->Find A Library

But still it gives me that warning. Any way we could edit the script to not use that function?

**Comment by airhadoken** [comment]
@rahulserver I had been sitting on making a new release that fixes that issue, because I was intending to add better DM support.  But I went ahead and made the new release, so if you use v23, that warning shouldn't happen now.

**Comment by rahulserver** [comment]
@airhadoken thanks man. yeah that fixed it!
Keep up the great work going :)
