### ISSUE TITLE
Find friends, favorites etc.

### ISSUE THREAD

**Issue by nm-de** [airhadoken/twitter-lib#21]
Hi, I've got this working perfectly for searching tweets and retweeting. But I'm looking for a way to find friends of a particular id or find tweets favorited by a user. Is there any way I can do it?

**Comment by airhadoken** [comment]
Hi @neeravmakwana, while there are no convenience functions in Twitter Lib for these particular actions, they can both be done through `new Twitterlib.OAuth(...).fetch()`

To find a user's recent favorites, pass the ID or screen name as a parameter to `https://api.twitter.com/1.1/favorites/list.json`.  More here: https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-favorites-list

And to find a user's friends (which are the people a user follows, by API definitions; contrast with followers (people who follow a user) and friendships (which is either how two users relate or a user's request to follow another user, depending on context)), pass the ID or screen name as a parameter to `https://api.twitter.com/1.1/friends/list.json`.  More for getting a user's friends here: https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-list

When using `fetch()`, the returned value is an object representing the whole response, but what you want is a parsed version of the body of the response.  To do that, here's some example code:

```
var service = new Twitterlib.OAuth(PropertiesService.getScriptProperties());
var response = service.fetch("https://api.twitter.com/1.1/friends/list.json?screen_name=air_hadoken");
var data  = JSON.parse(response.getContentText("UTF-8"));
Logger.log(data.users[0].screen_name); // -> "KLF_Ate_My_Kids"
```
