### ISSUE TITLE
Quote tweet

### ISSUE THREAD

**Issue by nm-de** [airhadoken/twitter-lib#22]
Hi, can you help me in figuring out how do I quote a tweet? I know the sendtweet function accepts tweet text, params and options. 
OAuth.prototype.sendTweet = function(tweet, params, options)

But I don't know how should I pass the quoted tweet URL or tweet ID to make my tweet quote another tweet.

I tried passing the tweet URL (in the form of https://twitter.com/statuses/<tweet_id>) to the function I am calling (by adding 'attachment_url=' at the front and passing as both params and options separately), but it keeps on giving me an error.

Thanks!

**Comment by airhadoken** [comment]
To quote a tweet, append the URL of the tweet to the end of the tweet text.

Here's how my bot @turtles_down constructs a tweet (after getting its own user account as an object):

```
  var status_text = "🐢\n\nhttps://twitter.com/" + user.screen_name + "/status/" + user.status.id_str;

  twit.sendTweet(status_text);
```

Newlines aren't necessary (used here for effect), but some whitespace before the URL is needed.
