### ISSUE TITLE
Restore Underscore dependency for TransientProperties and twitter.gs

### ISSUE THREAD

**Issue by airhadoken** [airhadoken/twitter-lib#30]
The TransientProperties class and fetchTweets() are currently unusable, as they both rely on Underscore.js and v24 removed that dependency.

**Comment by antgiant** [comment]
Oops. Sorry about that. I added it back in dev. Do you have an easy way to test this since clearly I missed it in my testing.

**Comment by airhadoken** [comment]
It broke a couple of my Twitter bots that were linking it in dev mode (which they really shouldn't have done).  Let me try them in dev mode again...

**Comment by antgiant** [comment]
Sorry :-(

**Comment by airhadoken** [comment]
There's two components to including Underscore.  One is linking in the library.  The other is making `_` available via `var _ = Underscore.load();` or `global._ = Underscore.load();`

That second part has to be a source change, so a PR is in order.

**Comment by antgiant** [comment]
Looks like the offending apps-script-oauth1 commit is [this one](https://github.com/gsuitedevs/apps-script-oauth1/commit/49754de62ca5d2b6f88061e6c8031a41fcf1e21a#diff-10cd394dc33d6d3581af08a668f2b45aL20). Working on reverting that now.

**Comment by airhadoken** [comment]
Merging #31 will be sufficient.  I've already put up the change in the script engine, so it's just a matter of merging here and publishing a new version there.  (Don't forget release notes!  :) )

**Comment by antgiant** [comment]
Ok. I'll go roll back [my version](https://github.com/airhadoken/apps-script-oauth1/commit/5e4c92660165ad57574575a1387c434ac09a8bc8) over in the apps-script-oauth1 repo. Think there is any value in adding the comment from mine to yours though?

**Comment by airhadoken** [comment]
I think it would be better added to the README in this repo, like in a "Self-Hosting" section.
