### ISSUE TITLE
Error: Exception: Limit Exceeded: URLFetch URL Length.

### ISSUE THREAD

**Issue by mangatinanda** [airhadoken/twitter-lib#34]
Have been using this lib for some time. Now getting this exception when using the method `fetchTweets`. 

Looks like there is a [limit on the length of URL](https://stackoverflow.com/questions/43142607/urlfetchapp-fetch-with-very-long-urls/43196448).  How to fix this?

**Comment by antgiant** [comment]
2kb is quite a bit of data. What all are you sending to fetchTweets that generates a URL that long?

**Comment by antgiant** [comment]
Closing due to lack of feedback. Please open a new issue if you are still experiencing this issue.
