### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by emilyanncr** [airhadoken/twitter-lib#36]
When I tried to add the id MKvHYYdYA4G5JJHj7hxIcoh8V4oX7X1M_ to my library it says: "Check the ID and access permissions and try again."
Can you please advise?  Thanks

**Comment by antgiant** [comment]
Hmm, looks like the new script editor now expects a different library ID. No idea why.

The ID the new editor expects is `11dB74uW9VLpgvy1Ax3eBZ8J7as0ZrGtx4BPw7RKK-JQXyAJHBx98pY-7`

**Comment by antgiant** [comment]
Thanks for letting me know. I've updated the instructions for everyone going forward.
