### ISSUE TITLE
tweet not getting posted through "service.sendTweet(status, params)" function despite successful authentication

### ISSUE THREAD

**Issue by om07mainhoonna** [airhadoken/twitter-lib#37]
My aim is to automate posting tweets at a particular date and time from google sheets.
For this, I have:
1. created my developer account
2. generated my access tokens and keys ("_Created with Read and Write permissions_")
3. turned on essential API access in the Twitter API Developer site
4. in authentication settings enabled OAuth1.0a (It shows"_OAuth 1.0a turned on_")
5. also imported **twitter-lib** using the project key for the script in my google apps script project for the google sheet

Below is my sheet:
![Google Sheet](https://user-images.githubusercontent.com/1733809/173487564-5046aba3-4545-47da-9ae2-41655a3c9bdd.jpeg)

I want to process my text in the sheet which I do in the function `prepareMyTweet1()` and then send it through the function `sendMyTweet1()`. I have edited bits and pieces of the original code from [this source](https://levelup.gitconnected.com/send-tweets-from-google-sheet-using-google-apps-script-d35382e901d8).

**Below is my code:**
```
function myFunction1() {

  prepareMyTweet1();

  sendMyTweet1();
  
}


function prepareMyTweet1() {
  // process my tweet text from google sheet
}


const twitterKeys = {
    TWITTER_CONSUMER_KEY: "my_key",
    TWITTER_CONSUMER_SECRET: "my_secret",
    TWITTER_ACCESS_TOKEN: "my_access_token",
    TWITTER_ACCESS_SECRET: "my_access_secret",
}


function sendMyTweet1() {
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();
  var startRowNumber = 2;
  var endRowNumber = sheet.getLastRow();

  var props = PropertiesService.getScriptProperties();
  props.setProperties(twitterKeys);
  var params = new Array(0);
  var service = new Twitterlib.OAuth(props);

  var myTweet;
  var identifier;
  
  for (var currentRowNumber = startRowNumber; currentRowNumber <= endRowNumber; currentRowNumber++) {
		var row = sheet.getRange(currentRowNumber + ":" + currentRowNumber).getValues();
    console.log("This the tweet text: ",row[0][2])
		// check that the second column (Date) is equal to today
		if (isToday1(row[0][0])) {
      myTweet = row[0][2];
			identifier = currentRowNumber - 1;
      if (!service.hasAccess()) {
		    console.log("Authentication Failed");
	    }
      else {
		    console.log("Authentication Successful");      
        var status = myTweet + "\n\n" + "#Automated #GoogleSheets";
		    try {
			    var response = service.sendTweet(status, params);
			    console.log("Response by Twitter: ",response);
		    }
        catch (e)
        {
          console.log("Error",e);
        }
	    }
      break;
		}
	}
}

function isToday1(date) {
	var today = new Date();
	var dateFromRow = new Date(date);
	return dateFromRow.getDate() == today.getDate() &&
		dateFromRow.getMonth() == today.getMonth() &&
		dateFromRow.getFullYear() == today.getFullYear()
}
```

**The execution log is as below:**
```
9:01:25 AM	Notice	Execution started
9:01:25 AM	Info	This the tweet text:  This is a test tweet
9:01:25 AM	Info	Authentication Successful
9:01:25 AM	Info	Send tweet failure. Error was:
{"name":"Exception"}

options were:
{"method":"POST","payload":"status=This%20is%20a%20test%20tweet%0A%0A%23Automated%20%23GoogleSheets","headers":{"Authorization":"OAuth oauth_consumer_key=\"my_key\", oauth_nonce=\"my_auth\", oauth_signature=\"my_signature\", oauth_signature_method=\"HMAC-SHA1\", oauth_timestamp=\"1655177485\", oauth_token=\"my_token\", oauth_version=\"1.0\""},"escaping":false}

9:01:25 AM	Info	Response by Twitter:  null
9:01:26 AM	Notice	Execution completed
```

I tried finding a solution on stackoverflow, but there is so little coverage on the topic that I am unable to find anything useful. The closest I got was with [this question](https://stackoverflow.com/questions/71058794/trying-to-use-twitterlib-25-with-gas/71085559#71085559). But again, this too isn't of much help in my case.

**Comment by antgiant** [comment]
My initial suspicion is your Twitter keys. I'm pretty sure I have gotten errors like that in the past when I got those wrong. I would also suggest double checking that a space didn't sneak in at the beginning or end of any of the keys. Depending how you copied them in that can easily happen.

If that doesn't work I'll take a swing at replicating your issue, and see where that takes us.

**Comment by om07mainhoonna** [comment]
@antgiant
I have tested my keys through postman and [here](https://twitter.com/7bluephoenix/status/1536563113814011904?s=20&t=5jMrrUfRouh578QYvJG4Pg) is the tweet.

Also I have rechecked my authentication keys, and IMO it should be working since the condition `!service.hasAccess()` returned _false_ confirming successful authentication. Let me know if I am missing something.

Also I just checked a [closed issue](https://github.com/airhadoken/twitter-lib/issues/35) wherein the user was facing similar issue. But he enabled **Elevated access** instead of **Essential access** which went on to resolve his problem. However I don't think that should really be the cause of my error as even the later has scope (500K tweets/month, though no caps for posting tweets I guess) for twitting through the API. Please let me know if I am wrong or if the Twitter API doc are missing a thing or two about this.
![image](https://user-images.githubusercontent.com/1733809/173495723-61ce88ba-b524-4b66-ad17-2d55aafe5303.png)

**Comment by om07mainhoonna** [comment]
@nidhinkumar06 can you provide any help?
I had taken the initial code from your article [here](https://levelup.gitconnected.com/send-tweets-from-google-sheet-using-google-apps-script-d35382e901d8).

**Comment by antgiant** [comment]
Hmm, I took your code pasted it into a fresh Google Sheet, updated cost twitterKeys with my own, and it posted the tweet fine. So, it isn't your code.
I logged into the the Twitter Developer portal to check permissions and the secrets I used are setup like this. 
![Screenshot 2022-06-15 211509](https://user-images.githubusercontent.com/938620/173970784-26d7da6f-20d3-446b-bbe6-c2aaa290c098.png)

It appears that the Essential vs Elevated only applies to OAuth 2.0 and my keys are set to OAuth 1.0a.
I would not be surprised at all if this library doesn't currently support OAuth 2.0. If I can find some time I will try to upgrade it to support OAuth 2.0. In the meantime I suggest creating OAuth 1.0 keys and secrets. They should work.

**Comment by om07mainhoonna** [comment]
@antgiant 
Thanks for taking your time out and the trouble to replicate the issue.

However, my keys have been created in the exact way as you mentioned. Here is the screenshot of my authentication settings for your reference.
![Screenshot_2022-06-16-07-40-07-95_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/1733809/173976399-5d580585-e297-4441-beb6-74f4353e38cc.jpg)

I agree with your observation and now I am really wondering now as to what is the exact cause of the issue 😅.

P.S. **Elevated Access** was [mentioned by another user](https://medium.com/@ighsight/works-perfectly-if-the-twitter-developer-account-you-are-using-has-elevated-access-76ab73662386) in the comments section in my [source article](https://levelup.gitconnected.com/send-tweets-from-google-sheet-using-google-apps-script-d35382e901d8) which I encountered again yesterday. Hence, I have applied for **Elevated Access**, just in case it somehow has any influence on the outcome. Will keep you posted as and when Twitter grants it to me and I'm able to test it out again.

**Comment by antgiant** [comment]
You might be right. My keys do have elevated access apparently. Something else for me to investigate. (I'm pretty sure that when I created those keys elevated Access didn't exist. 🤷‍♂️)

**Comment by om07mainhoonna** [comment]
@antgiant 
That was the main reason I was confused as Twitter docs do not mention anything about this weird anamoly.
And the things that are there in it, make it clear that anything related to **Elevated Access** is to do with **Oauth 2.0** and not **Oauth 1.0a**.

Since I have tested/used the keys to tweet using postman (which maintains Twitter cookies) does it consider as development environment, which is the limit for **Essential Access**? And then doesn't allow my GAS to use them as it considers it as another development environment? That's what I'm wondering about.

Anyways, if and when I'm granted the **Elevated Access**, I'll test and provide an update which could help others.

**Comment by antgiant** [comment]
Checking in on this. Were you successful?

Also, just pushed out https://github.com/airhadoken/twitter-lib/pull/38 which should provide more helpful error messages here if you are still having this issue.

**Comment by antgiant** [comment]
Found out that error messages were being severely truncated. 

Latest version of the library should resolve that and give much more informative error messages.

**Comment by om07mainhoonna** [comment]
@antgiant
I've not yet been provided the **Elevated Access** by Twitter. In awaiting a response from them since last 11 days. If and when I'm granted that, will test it out.

Thanks for the update. I haven't tried out the latest version for checking the error message. Will check and revert once I'm able to test it.
Thanks 👍🏻

**Comment by antgiant** [comment]
Thanks for the update. Might be worth trying even without elevated access now that there are much better error messages. Up to you.

**Comment by om07mainhoonna** [comment]
@antgiant 
Just tested it with the same code and updated library version (log below).
I do getting more details about the error now explaining its cause.
Thanks.

```
9:37:48 AM	Notice	Execution started
9:37:47 AM	Info	This is your tweet text:  This is a test tweet
9:37:47 AM	Info	Authentication Successful
9:37:48 AM	Info	Send tweet failure. Error was:
Exception: Request failed for https://api.twitter.com returned code 403. Truncated server response: {"errors":[{"message":"You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpo... (use muteHttpExceptions option to examine full response)

options were:
{"method":"POST","payload":"status=This%20is%20a%20test%20tweet%0A%0A%23Automated%20%23GoogleSheets","headers":{"Authorization":"OAuth oauth_consumer_key=\"my_key\", oauth_nonce=\"my_auth\", oauth_signature=\"my_signature\", oauth_signature_method=\"HMAC-SHA1\", oauth_timestamp=\"1656302868\", oauth_token=\"my_towken\", oauth_version=\"1.0\""},"escaping":false}

9:37:48 AM	Info	Response by Twitter:  null
9:37:50 AM	Notice	Execution completed
```

**Comment by airhadoken** [comment]
Closed due to the project moving to archived.
