### ISSUE TITLE
Time to shut down this library?

### ISSUE THREAD

**Issue by antgiant** [airhadoken/twitter-lib#39]
As of [April 29, 2023 Twitter appears to be fully shutting down all V 1 APIs](https://twittercommunity.com/t/announcing-new-access-tiers-for-the-twitter-api/188728) and switching to v2 APIs only. Since this is a V 1 API library, I think that someone else may need to take up the mantle of creating a V2 version of this repo.

I'd be happy to be proved wrong, but I believe this may be the end for this library.

**Comment by airhadoken** [comment]
Agreed.  Time to archive.

**Comment by airhadoken** [comment]
Thanks for your admin work on this project, @antgiant
