### ISSUE TITLE
Evil-eval() service references & other hacks to prevent huge list of unused permission requirements.

### ISSUE THREAD

**Issue by airhadoken** [airhadoken/twitter-lib#4]
Currently Twitter Lib requires authorization to use Document Service, Spreadsheet service, Mail service, etc. even when it's not needed.  These can be accessed on-demand instead by doing e.g. `eval('Spreadsheet' + 'App').getUi();` instead of `SpreadsheetApp.getUi();`

Plus, since the only place where the `container` property is used is determining how to access the user's UI when doing two-step\* authorization, don't bother going through the try-catch flow on object creation.  Wait until it's needed.

---

*two-step auth is used when the user hasn't pre-set an access token; the flow to set an access token is presented to the user of a document or spreadsheet, or mailed to the user if nonesuch exists

**Comment by airhadoken** [comment]
And of course, the user can skip this entirely by setting the container property manually.

**Comment by airhadoken** [comment]
Hm.  evil-eval isn't actually taking the permissions line items off.

On review.  I don't think this is possible.  Closing.

**Comment by hudcap** [comment]
There seems to be a way to control permission requests using the manifest file.
Details [here](https://developers.google.com/apps-script/concepts/scopes#setting_explicit_scopes).
I'm not certain that it works for a library, but it worked for my script that uses your library.

Thanks for a great library!
